### PR TITLE
Allow newer apiKey use

### PR DESCRIPTION
**Pull request by PurHur**
The api now expects an apiKey to be present in the http headers.

The tests `testGetDataPriceHistorical` is failing. But i have no idea what you did test there. Please help me here :)

### CODE REVIEW

**Comment by PurHur** [comment]
i also moved phpunit to the dev dependencies

**Comment by nuryagdym** [comment]
Your getDataPriceHistorical function workes perfectly when I test it. I did not run your test cases, but running getDataPriceHistorical  method of Historical.php is working. 
Also why don't you use
`$_tsyms = implode(',', $tsyms);`
instead of 
`        foreach ($tsyms as $i => $tsym ) {
            if ($i == 0 ) {
                $_tsyms = $tsym;
            } else {
                $_tsyms = $_tsyms . "," . $tsym;
            }
        }`
in your getDataPriceHistorical  method (and in all other methods)

**Comment by PurHur** [comment]
i was reffering to the test cases. The method works but the test case espects a count bigger than 1 and its exactly one.... it should be one :)

If this repo now gets some attention. Do you want to make some refactoring commits?

**Comment by nuryagdym** [comment]
When I run this code it works as it should;
`		$historical = new Cryptocompare\Historical();
		$response = $historical->getDataPriceHistorical($tryConversion = "true", $fsym = "BTC", $tsyms = array("USD","EUR"), $ts = "1507469305", $e = "CCCAGG", $sign = "false");
		$c = count((array) $response); //value of $c == 1`
so your test case should not fail.
I would be happy to help you if I will be still working at the same company (project) by that time :)

**Comment by PurHur** [comment]
hmpf i just saw that the most important commit is missing (actually use the key!). Wait for tomorrow and i deliver it... I think now its just the default ip based rate limit as always.

**Comment by loeken** [comment]
hey guys, just saw this. changes look good to me, so i ll merge it. personally not the biggest fan of the hardcoded api key. but instead of blocking it i ll rather merge it ;)

**Comment by PurHur** [comment]
I want to highlight these words for the future

> but instead of blocking it i ll rather merge it

this should be said more often.

**Pull request merged**
